title: Eggsample Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://example.com
theme: /opt/build/repo/themes
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: 雙龍體育
      category: North Coast
      partial:
    - name: Backup Gateway
      category: North Coast
    - name: 雙龍體育
      description: The web frontend for the application.
      category: Uncategorized
      link: https://ssangyongsportsweb.blogspot.com/
    - name: API
      description: The guts of the application.
      category: Uncategorized
    - name: Media Proxy
      description: This is the service responsible for serving images, audio, and
        video. It is reliant on our CDN.
      category: Uncategorized
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs:
    - name: Monitoring
      link: https://httpsssangyongservice-centerwebnodetw.instatus.com/summary.json
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: North Coast
      description: The main servers are located here.
      closed: true
    - name: Empty Category
    - name: Uncategorized
      untitled: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
