title: Eggsample Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://example.com
theme: /opt/build/repo/themes
preserveTaxonomyNames: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC â€” Jan 2
  down: "#e60000"
  systems:
    - name: Gateway
      category: North Coast
    - name: Backup Gateway
      category: North Coast
    - name: Website
      description: The web frontend for the application.
      category: Uncategorized
      link: https://aswfcdass.com
    - name: API
      description: The guts of the application.
      category: Uncategorized
    - name: Media Proxy
      description: This is the service responsible for serving images, audio, and
        video. It is reliant on our CDN.
      category: Uncategorized
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/2022-02-28-004341-removebg-preview-1-1-5-.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs:
    - name: website
      link: https://aswfcdass.com/
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: North Coast
      description: The main servers are located here.
      closed: true
    - name: Empty Category
    - name: Uncategorized
      untitled: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: false
  useLargeHeaderDesign: true
customTabs:
  - name: Monitoring
    link: https://rss.uptimerobot.com/u1392810-a6115cc531ba608b59a049ad46a0cb80
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
